#!/usr/bin/env bash
#script that transfer afile from our client to server
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else 
	if [ "$4" ]
	then
		scp "$1" "$3"@"$2":"~/";
	else
		scp -i "$4" "$1" "$3"@"$2":"~/";
	fi
fi;
