#!/usr/bin/env bash
#script that transfer afile from our client to server
if [ $# -lt 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
else 
	scp "$1" "$3"@"$2" -i "$4"
fi
