#!/usr/bin/env bash
#install nginx in my server web-o1 server
sudo apt update;
sudo apt-get -y install nginx;
echo "Hello World!" | sudo tee /var/www/html/index.html;
sudo ufw enable;
sudo ufw allow 'Nginx HTTP';
sudo /etc/init.d/nginx start
