#!/usr/bin/env bash
#install nginx in my server web-o1 server
sudo apt update;
sudo apt-get -y install nginx;
echo "Hello World!" | sudo tee /var/www/html/index.html;
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo ufw enable;
sudo ufw allow 'Nginx HTTP';
sudo /etc/init.d/nginx start
