#!/usr/bin/env bash
#install nginx in my server web-o1 server
apt update;
apt-get -y install nginx;
echo "Hello World!" > /var/www/html/index.html;
echo 'server {
    listen 80;
    server_name 35.174.204.151;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        # Your existing server configuration goes here
        # ...
    }
}'> /etc/nginx/sites-available/redirect.conf
ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/
sed -i 's/world/world/' /var/www/html/index.html
ufw allow 'Nginx HTTP';
/etc/init.d/nginx start
