#!/usr/bin/env bash
# Configure Nginx server in a ubuntu server 16.04
# make a redirection 301 
# make a 404 not found page
# configure a response header

sudo apt update &&
sudo apt -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Holberton School for the win!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "/listen 80 default_server/a add_header X-Served-By \"$HOSTNAME\";" /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
service nginx start
