#!/usr/bin/env bash
#install nginx in my server web-o1 server
sudo apt update;
sudo apt-get -y install nginx;
echo "Hello World!" | sudo tee /var/www/html/index.html;
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/my_404.html
sed -i '/listen 80 default_server/a error_page 404 /my_404.html; location = /my_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default

sudo ufw enable;
sudo ufw allow 'Nginx HTTP';
sudo /etc/init.d/nginx start
