#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
apt-get update
apt-get -y install haproxy
frontend http
  bind *:80
  mode http
  default_backend web-backend
backend web-backend
   balance roundrobin
   server 272632-web-01 35.174.204.151 check
   server 272632-web-02 54.89.179.146 check

