#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument.
if [ ! $# -eq 0 ] && [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    ping "$1"
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
