#!/usr/bin/env bash
# nginx like port 80
apt-get update
apt-get -y install curl
sed -i 's/8080/80/g' /etc/nginx/sites-available/default
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
sudo service nginx restart 
