#!/usr/bin/env bash
#Bash script that displays To infinity and beyond indefinitely.
echo $$|tee sudo /var/run/myscript.pid
trap "sudo echo 'I hate the kill command'; sudo rm/var/run/myscript.pid" SIGTERM
trap "sudo echo 'Y U no love me?!'" SIGINT
trap "sudo rm /var/run/myscript.pid" SIGQUIT 

while true
do
echo "To infinity and beyond";
done
