#!/usr/bin/env bash
#Tha advance 2
if [ "$1" = "start" ]
then
sudo bash ./manage_my_process &
echo "$$" |sudo tee /var/run/my_process.pid &
echo "manage_my_process started"
elif [ "$1" = "stop" ]
then
pkill -9 -f "manage_my_process" &
sudo rm /var/run/my_process.pid &
echo "manage_my_process stopped"
elif [ "$1" = "restart" ]
then
pkill -9 -f "manage_my_process" &
sudo rm /var/run/my_process.pid &
sudo bash ./manage_my_process &
echo "$$" |sudo tee /var/run/my_process.pid 
echo "manage_my_process restarted"
else
echo "Usage: manage_my_process {start|stop|restart}"
fi