#!/usr/bin/env bash
# my prints best School 10 times
i=1
while [ $i -le 10 ]
do
    st="Best School"
    if [ $i = 4 ];
    then echo "bad luck";
    elif [ $i = 8 ];then
    echo "good luck";
    else
	echo "$st";

    fi

    ((i++))
done
