#!/usr/bin/env bash
#a Bash script that configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.new
sed -i 's/127\.0\.0\.1\s*localhost/127.0.0.2 localhost/g' ~/hosts.new
echo -e "\n8.8.8.8  facebook.com" | tee ~/hosts.new
cp -f ~/hosts.new /etc/hosts
