#!/usr/bin/env bash
#Run Nginx as Nginx\
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown -R nginx /etc/nginx
chmod 644 /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
