#!/usr/bin/env bash
# Configure the nginx user to run nginx
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod ugo+wrx /etc/nginx/nginx.conf | sudo -u nginx service nginx restart
